# Agent Handoff Automation Configuration

## Enabled Features
handoff_issues: true          # Create GitHub issues for handoffs
update_coordination_files: true # Auto-update @current-work, @blockers
blocker_summary: true         # Create/update blocker summary issue
metrics_update: true          # Run metrics after handoff
notifications: true           # Send notifications (when configured)

## Agent Mapping
# Map agent names to GitHub usernames for auto-assignment
# Format: agent_name: github_username
agent_github_mapping:
  "@arch-01": "architect-user"
  "@backend-01": "backend-user"
  "@frontend-01": "frontend-user"
  "@fullstack-01": "fullstack-user"
  "@test-01": "test-user"
  "@devops-01": "devops-user"

## Notification Channels
# Configure where to send handoff notifications
notifications:
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#agent-handoffs"
    
  discord:
    enabled: false
    webhook_url: "${DISCORD_WEBHOOK_URL}"
    
  email:
    enabled: false
    smtp_config: "${SMTP_CONFIG}"
    
## Labels
# GitHub labels to use (will be created if don't exist)
labels:
  handoff: "handoff"
  coordination: "agent-coordination"
  blocker: "blocker"
  priority: "priority"
  
## Templates
# Issue title templates
issue_title_template: "[Handoff] {task} - {next_agent}"
blocker_title_template: "🚧 Active Blockers - Action Required"

## Rules
# Automation behavior rules
rules:
  auto_close_completed_handoffs: true    # Close issue when next agent completes
  handoff_timeout_hours: 48              # Alert if handoff not acknowledged
  require_handoff_acceptance: false      # Require explicit acceptance
  update_metrics_on_handoff: true        # Run metrics script
  
## Triggers
# What triggers handoff detection
triggers:
  commit_message_pattern: "Handoff:[[:space:]]*(@[a-zA-Z]+-[0-9]+)"
  pr_body_pattern: "To[[:space:]]Agent:[[:space:]]*(@[a-zA-Z]+-[0-9]+)"
  branch_pattern: "feature/.*-handoff-.*"
