services:
  # Backend API Service
  - type: web
    name: todo-app-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && npm run build && npm run migrate
    startCommand: cd backend && npm run start:prod
    envVars:
      # Database
      - key: DATABASE_URL
        fromDatabase:
          name: todo-app-db
          property: connectionString
      
      # Redis
      - key: REDIS_URL
        fromService:
          name: todo-app-redis
          type: redis
          property: connectionString
      
      # JWT Secrets
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      
      # Application
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        value: https://your-frontend.vercel.app
      
      # Email (user needs to configure)
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        value: noreply@yourdomain.com
      
      # OAuth (user needs to configure)
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      
      # Security
      - key: CSRF_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      
      # Optional: Sentry
      - key: SENTRY_DSN
        sync: false
      
      # Optional: S3 for file uploads
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_REGION
        value: us-east-1

    healthCheckPath: /api/v1/health
    autoDeploy: true
    
  # Redis Service
  - type: redis
    name: todo-app-redis
    plan: free
    ipAllowList: []

databases:
  - name: todo-app-db
    plan: free
    databaseName: tododb
    user: todouser

envVarGroups:
  - name: todo-app-secrets
    envVars:
      # Add your secrets here after deployment
      - key: SMTP_USER
        value: your-email@gmail.com
      - key: SMTP_PASS
        value: your-app-password
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret
      - key: GITHUB_CLIENT_ID
        value: your-github-client-id
      - key: GITHUB_CLIENT_SECRET
        value: your-github-client-secret
      - key: SENTRY_DSN
        value: your-sentry-dsn