name: Deploy Backend to Render

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'shared/**'
      - '.github/workflows/deploy-render.yml'
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    # Run tests before deployment
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Run tests
      working-directory: ./backend
      run: npm test
      env:
        NODE_ENV: test
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
    
    # Deploy to Render
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": false}' \
          "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys"
    
    # Wait for deployment
    - name: Wait for deployment
      run: sleep 60
    
    # Health check
    - name: Health check
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.RENDER_BACKEND_URL }}/health)
        if [ $response -eq 200 ]; then
          echo "✅ Health check passed"
        else
          echo "❌ Health check failed with status $response"
          exit 1
        fi
    
    # Notify on success
    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Backend deployed successfully to Render" >> $GITHUB_STEP_SUMMARY
        echo "URL: ${{ secrets.RENDER_BACKEND_URL }}" >> $GITHUB_STEP_SUMMARY
    
    # Notify on failure
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Backend deployment to Render failed" >> $GITHUB_STEP_SUMMARY