name: Deploy Frontend to Vercel

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'shared/**'
      - '.github/workflows/deploy-vercel.yml'
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    # Run tests before deployment
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Run tests
      working-directory: ./frontend
      run: npm test
      env:
        NODE_ENV: test
    
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      env:
        VITE_API_URL: ${{ secrets.RENDER_BACKEND_URL }}
        VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN_FRONTEND }}
    
    # Deploy to Vercel
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./frontend
        vercel-args: '--prod'
    
    # Get deployment URL
    - name: Get deployment URL
      id: deployment
      run: |
        echo "url=${{ steps.vercel.outputs.preview-url }}" >> $GITHUB_OUTPUT
    
    # Health check
    - name: Health check
      run: |
        sleep 30
        response=$(curl -s -o /dev/null -w "%{http_code}" https://${{ steps.deployment.outputs.url }})
        if [ $response -eq 200 ]; then
          echo "✅ Health check passed"
        else
          echo "❌ Health check failed with status $response"
          exit 1
        fi
    
    # Notify on success
    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Frontend deployed successfully to Vercel" >> $GITHUB_STEP_SUMMARY
        echo "URL: https://${{ steps.deployment.outputs.url }}" >> $GITHUB_STEP_SUMMARY
    
    # Notify on failure
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Frontend deployment to Vercel failed" >> $GITHUB_STEP_SUMMARY